package com.spring.demo.springbootexample.mybatis.mapper;

import com.spring.demo.springbootexample.mybatis.po.Hello;
import com.spring.demo.springbootexample.mybatis.po.HelloExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HelloMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbggenerated Fri May 04 11:16:01 CST 2018
     */
    int countByExample(HelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbggenerated Fri May 04 11:16:01 CST 2018
     */
    int deleteByExample(HelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbggenerated Fri May 04 11:16:01 CST 2018
     */
    int insert(Hello record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbggenerated Fri May 04 11:16:01 CST 2018
     */
    int insertSelective(Hello record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbggenerated Fri May 04 11:16:01 CST 2018
     */
    List<Hello> selectByExample(HelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbggenerated Fri May 04 11:16:01 CST 2018
     */
    int updateByExampleSelective(@Param("record") Hello record, @Param("example") HelloExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hello
     *
     * @mbggenerated Fri May 04 11:16:01 CST 2018
     */
    int updateByExample(@Param("record") Hello record, @Param("example") HelloExample example);
}